// internal/ui/jump_parent_test.go
//
// `gp` (jump to a thread's parent message) chord tests. Reuses the
// pendingLinkNav machinery permalinks use, so the interesting cases are
// the three states the parent can be in: on screen, in another channel,
// or nothing selected at all.
package ui

import (
	"testing"

	"github.com/gammons/slk/internal/cache"
	"github.com/gammons/slk/internal/ids"
	"github.com/gammons/slk/internal/ui/help"
	"github.com/gammons/slk/internal/ui/messages"
	"github.com/gammons/slk/internal/ui/sidebar"
)

func TestChord_GP_SelectsParentInActiveChannel(t *testing.T) {
	a := newTestAppWithMessages(t)
	a.activeChannelID = "C1"
	a.focusedPanel = PanelMessages
	_ = a.openThreadPanel(messages.MessageItem{TS: "1.0"}, "C1", "1.0")
	if !a.threadVisible {
		t.Fatal("setup: thread panel should be open")
	}
	// Cursor elsewhere, so selecting the parent is an observable move.
	a.messagepane.SelectByTS("2.0")

	_ = press(a, 'g')
	_ = press(a, 'p')

	if a.threadVisible {
		t.Error("thread panel still open; it would cover the message just jumped to")
	}
	if got := a.messagepane.SelectedIndex(); got != 0 {
		t.Errorf("selected index = %d; want 0 (the parent at ts 1.0)", got)
	}
}

func TestChord_GP_ParentInAnotherChannelSwitchesFirst(t *testing.T) {
	a := newTestAppWithMessages(t)
	a.activeChannelID = "C1"
	a.view = ViewThreads
	a.SetChannels([]sidebar.ChannelItem{{ID: "C2", Name: "design", Type: "channel"}})
	a.SetChannelService(NewChannelService(ChannelServiceFuncs{
		Lookup: func(id ids.ChannelID) (string, string, bool) {
			return "design", "channel", id == "C2"
		},
	}))
	a.threadsView.SetSummaries([]cache.ThreadSummary{
		{ChannelID: "C2", ChannelName: "design", ThreadTS: "9.0", ParentTS: "9.0"},
	})

	_ = press(a, 'g')
	cmd := press(a, 'p')

	if cmd == nil {
		t.Fatal("no command; expected a channel switch toward the parent's channel")
	}
	sel, ok := cmd().(ChannelSelectedMsg)
	if !ok {
		t.Fatalf("cmd produced %T; want ChannelSelectedMsg", cmd())
	}
	if sel.ID != "C2" {
		t.Errorf("switching to %q; want C2", sel.ID)
	}
	// The selection can't happen yet — C2's messages aren't loaded. The
	// pending nav is what completes it once they arrive.
	if a.pendingLinkNav == nil || a.pendingLinkNav.messageTS != "9.0" {
		t.Errorf("pendingLinkNav = %+v; want one targeting ts 9.0", a.pendingLinkNav)
	}
}

func TestChord_GP_NoThreadSelectedToasts(t *testing.T) {
	a := newTestAppWithMessages(t)
	a.focusedPanel = PanelMessages

	_ = press(a, 'g')
	cmd := press(a, 'p')

	if cmd == nil {
		t.Fatal("no command; expected a toast explaining nothing was selected")
	}
	toast, ok := cmd().(ToastMsg)
	if !ok {
		t.Fatalf("cmd produced %T; want ToastMsg", cmd())
	}
	if toast.Text == "" {
		t.Error("empty toast text")
	}
}

// The chord must not swallow keys it doesn't own: `g` followed by
// anything else falls through to normal handling.
func TestChord_GP_DisarmsAfterUse(t *testing.T) {
	a := newTestAppWithMessages(t)
	a.focusedPanel = PanelMessages

	_ = press(a, 'g')
	_ = press(a, 'p')

	if a.pendingG {
		t.Error("pendingG still armed after gp; the next keypress would be misread")
	}
}

// The `?` overlay is generated by reflection over the keymap, so a
// chord handled as a bare keypress would work but stay undiscoverable.
func TestChord_GP_AppearsInHelpOverlay(t *testing.T) {
	a := newTestAppWithMessages(t)

	var found bool
	for _, e := range help.FromKeyMap(a.keys) {
		if e.Key == "gp" {
			found = true
		}
	}
	if !found {
		t.Error("gp missing from the help overlay entries")
	}
}
